version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: iso_compliance_db
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: iso_compliance
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iso_compliance_app
    environment:
      DATABASE_URL: mysql://root@mysql:3306/iso_compliance
      NEXTAUTH_SECRET: 34ae0d3dca4eee61472523fc31990507a24ffa915b81a25c51d30299960f840e
      NEXTAUTH_URL: http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    container_name: iso_compliance_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
